import os
import requests
import yfinance as yf
import pandas as pd
import ccxt
from datetime import datetime

# --- 設定你的 Telegram 參數 (測試時可以直接填入，自動化時建議用環境變數) ---
TG_TOKEN = "你的_TOKEN_貼在這裡"  # 例如 "123456:ABC..."
TG_CHAT_ID = "你的_CHAT_ID_貼在這裡" # 例如 "987654321"

# 如果是 GitHub Actions 自動化，會從環境變數讀取 (稍後教學會用到)
if 'TG_TOKEN' in os.environ: TG_TOKEN = os.environ['TG_TOKEN']
if 'TG_CHAT_ID' in os.environ: TG_CHAT_ID = os.environ['TG_CHAT_ID']

def get_data():
    # 1. 抓取宏觀數據
    print("正在抓取數據...")
    tickers = ["^VIX", "^VVIX", "BTC-USD"]
    data = yf.download(tickers, period="1y", progress=False)
    
    # 處理 yfinance 格式
    def get_series(ticker):
        try:
            if 'Close' in data.columns:
                df = data['Close']
                if isinstance(df, pd.DataFrame): return df[ticker]
                return df
            return data.iloc[:, 0] # Fallback
        except:
            return None

    vix = get_series("^VIX")
    vvix = get_series("^VVIX")
    btc = get_series("BTC-USD")
    
    # 2. 抓取幣安數據
    binance = ccxt.binance()
    try:
        funding = binance.fapiPublic_get_premiumindex({'symbol': 'BTCUSDT'})
        fr = float(funding['lastFundingRate']) * 100
    except:
        fr = 0.0

    return vix, vvix, btc, fr

def analyze_and_send():
    vix, vvix, btc, fr = get_data()
    
    # 取最新值
    cur_vix = float(vix.iloc[-1])
    cur_vvix = float(vvix.iloc[-1])
    cur_btc = float(btc.iloc[-1])
    
    # 計算 Mayer Multiple
    ma200 = btc.rolling(window=200).mean().iloc[-1]
    mayer = cur_btc / ma200
    
    # --- 生成報告內容 ---
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    # 判斷信號
    signal_text = "⚖️ **震盪觀望**"
    if cur_vix > 30 and mayer < 0.8:
        signal_text = "🚀 **鑽石買點 (雙重共振)**\n建議：大資金分批進場"
    elif mayer < 0.8:
        signal_text = "💎 **價值低估 (Mayer < 0.8)**\n建議：開啟定投"
    elif cur_vix > 30:
        signal_text = "🔥 **宏觀恐慌 (VIX > 30)**\n建議：左側接刀"
    elif mayer > 2.4:
        signal_text = "🔴 **頂部風險 (Mayer > 2.4)**\n建議：分批止盈"
    elif fr < -0.01:
        signal_text = "⚡ **軋空機會 (費率負值)**\n建議：短線做多"

    # 組合訊息 (Markdown 格式)
    message = f"""
📊 **Phyrex 宏觀日報** ({date_str})
---------------------------
**{signal_text}**
---------------------------
**1. 宏觀恐慌指標**
• VIX (恐慌): `{cur_vix:.2f}` (警戒: 30)
• VVIX (波動): `{cur_vvix:.2f}` (警戒: 110)

**2. 比特幣價值錨**
• 現價: `${cur_btc:,.0f}`
• 估值 (Mayer): `{mayer:.2f}`
  *(<0.8 抄底 / >2.4 逃頂)*

**3. 短線情緒**
• 資金費率: `{fr:.4f}%`
---------------------------
_Generated by Python Automation_
"""
    
    # 發送請求
    url = f"https://api.telegram.org/bot{TG_TOKEN}/sendMessage"
    payload = {
        "chat_id": TG_CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }
    
    try:
        resp = requests.post(url, json=payload)
        if resp.status_code == 200:
            print("✅ 訊息發送成功！")
        else:
            print(f"❌ 發送失敗: {resp.text}")
    except Exception as e:
        print(f"❌ 錯誤: {e}")

if __name__ == "__main__":
    analyze_and_send()
